version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: visual-prompt-builder
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Development environment with hot-reload
  dev:
    build:
      context: .
      target: build
    command: sh -c "yarn dev --host"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
